use_frameworks!

platform :ios, '9.0'

target 'DPGodChati_Example' do
  pod 'DPGodChati', :path => '../'

  target 'DPGodChati_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
